name: solar_erp_app
description: Imt-Billbook mobile app for sales and operations.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.2.1
  dio: ^5.9.1
  flutter_secure_storage: ^10.0.0
  shared_preferences: ^2.5.4
  google_fonts: ^8.0.1
  flutter_animate: ^4.5.2
  fl_chart: ^1.1.1
  intl: ^0.20.2
  path_provider: ^2.1.5
  open_filex: ^4.7.0
  url_launcher: ^6.3.2
  share_plus: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/logo/logo.png
